AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Función para consolidar la

Parameters:

  BucketOrigen:
    Description: Nombre del bucket con los objetos crudos
    Default: default
    Type: String
  BucketDestino:
    Description: Nombre del bucket con los objetos procesados y particionados por día
    Default: default
    Type: String

Resources:

    LambdaFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: lambda.lambda_handler
            Runtime: python3.12
            Architectures: 
              - arm64
            CodeUri: lambda/
            Layers: 
              - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python312-Arm64:2
            # Pandas managed Layer https://aws-sdk-pandas.readthedocs.io/en/stable/layers.html
            MemorySize: 1512
            Policies:
              - Version: '2012-10-17'
                Statement:
                  - Sid: S3List
                    Effect: Allow
                    Action:
                      - s3:ListAllMyBuckets
                    Resource: 
                      - !Join [ "", [ "arn:aws:s3:::", !Ref BucketOrigen ] ]
                      - !Join [ "", [ "arn:aws:s3:::", !Ref BucketDestino ] ]
                  - Sid: S3
                    Effect: Allow
                    Action:
                      - s3:PutObject
                      - s3:GetObject
                      - s3:ListBucket
                    Resource: 
                      - !Join [ "", [ "arn:aws:s3:::", !Ref BucketOrigen ] ]
                      - !Join [ "", [ "arn:aws:s3:::", !Ref BucketDestino ] ]
            Environment:
                Variables:
                    BucketOrigen: !Ref BucketOrigen
                    BucketDestino: !Ref BucketDestino
