name: Actualiza listado de sensores

on:
  push:
    paths:
    - 'src/lambda.yml'
    - 'src/lambda/lambda.py'
  workflow_dispatch:

jobs:
  lambda:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configura credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Despliegue a AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: actualiza-aire-medellin-diario
          template: src/lambda.yaml
          parameter-overrides: "file:///${{ github.workspace }}/src/parameters.json"
          capabilities: CAPABILITY_AUTO_EXPAND