name: Actualiza listado de sensores

# Controls when the action will run.
on:
  push:
    paths:
    - 'data/sensores.json'
  # schedule:
  #   # Every day, 00:00.
  #   - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  actualiza_sensores:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Actualiza Sensores
        run: |
          pip install -r requirements.txt
          python ./data/actualizar_sensores.py
