name: Actualiza listado de sensores

# Controls when the action will run.
on:
  push:
    paths:
    - 'data/sensores.json'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  actualiza_sensores:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Instala Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Actualiza Sensores
        run: |
          pip install -r requirements.txt
          python ./data/actualizar_sensores.py
        env:
          PURPLEAIR_GROUP_ID: ${{ secrets.PURPLEAIR_GROUP_ID }}
          PURPLEAIR_READ_KEY: ${{ secrets.PURPLEAIR_READ_KEY }}
          PURPLEAIR_WRITE_KEY: ${{ secrets.PURPLEAIR_WRITE_KEY }}
