name: Actualiza listado de sensores

# Controls when the action will run.
on:
  push:
    branches:
      - dev
  # schedule:
  #   # Every hour, 1 minute past the hour.
  #   - cron: "1 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  actualiza_sensores:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Actualiza Sensores
        run: python test.py
