name: Hourly update

# Controls when the action will run.
on:
  push:
    branches:
      - dev
  # schedule:
  #   # Every hour, 1 minute past the hour.
  #   - cron: "1 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  hourly_update:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Sensores Actuales
        run: |
          curl --location 'https://api.purpleair.com/v1/groups/${{ secrets.PURPLEAIR_GROUP_ID }}' --header 'X-API-Key: ${{ secrets.PURPLEAIR_READ_KEY }}' --output sensores_actuales.json

      - name: Test1
        run: |
          cat sensores_actuales.json
