name: Upload to S3

on: [workflow_dispatch]

# jobs:
#   upload:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - uses: shallwefootball/s3-upload-action@master
#         with:
#           aws_key_id: ${{ secrets.AWS_KEY_ID }}
#           aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
#           aws_bucket: ${{ secrets.AWS_BUCKET }}
#           source_dir: 'data'

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: List buckets
      run: |
        aws s3 ls
    - name: Copy files to the test website with the AWS CLI
      run: |
        cd data
        aws s3 sync . s3://${{ secrets.AWS_BUCKET }}